if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("TCGAbiolinks")
BiocManager::install("SummarizedExperiment")
BiocManager::install("AnnotationDbi")
BiocManager::install("org.Hs.eg.db")

library(TCGAbiolinks)
library(SummarizedExperiment)
library(dplyr)
library(AnnotationDbi)
